### ISSUE TITLE
Concerns About Current Project Management 

### ISSUE THREAD

**Issue by Trigus42** [ryujinx-mirror/ryujinx#26]
Hi, I appreciate you, @regginator, trying to pick up this project, but I would like to express some concerns regarding the current project management practices that I believe warrant attention.

I view the deletion of issues as problematic, as it obscures the project's history and hinders transparency. Issues often contain valuable discussions and insights that can benefit current and future contributors. Additionally, when critical issues are removed, it can lead contributors to feel that their feedback is not valued or that dissenting opinions are being silenced. While the criticism may sometimes be unfounded or overblown, deleting issues such as #23 creates an impression of a lack of transparency and censorship, which can undermine trust. I wouldn't even have known this issue ever existed, had I not been mentioned in it. This perception can discourage open dialogue and engagement.  
Instead of deleting issues, I suggest we consider closing them with appropriate labels to maintain a clear record of past discussions.

Another (though much smaller) concern is that given the size and complexity of our project, I believe establishing a dedicated Discord community might be more effective than reusing the existing server. A focused space would allow for better collaboration and ensure that discussions remain relevant to this project, which is important if we want to keep it alive in the long term.

**Comment by regginator** [comment]
I agree, things are scaling up quite fast, but deleting #23 probably wasn't the best course of action yesterday, as I originally just claimed it as bait. For reference, I can post logs for #23 here, as well as my responses:

![Screenshot_20241004_070038](https://github.com/user-attachments/assets/917b4c3d-bc97-48fd-9a14-a676b3a2f97b)
![image-300](https://github.com/user-attachments/assets/c1a436a0-94d2-479d-ac01-1a18dcf23852)
![Screenshot_20241004_070323](https://github.com/user-attachments/assets/ba7d5fca-0c3b-4d73-8a0e-2296989da042)

As far as Discord goes, multiple people have requested this all be part of a separate server from Latte, which I definitely agree with as considering how bloated and chaotic Latte already is, lol. I will set all of that up later today

**Comment by TheGreatSageEqualToHeaven** [comment]
@regginator is great at listening I see. Like Reggie said himself there will be a dedicated server for ryujinx-mirror instead of using the Latte server (which is in reality a horrible place to be redirecting folks interested in emulating or contributing)

![image](https://github.com/user-attachments/assets/d8cd0495-6976-4e69-9cd3-3b51a7a3fba0)
-
Here is the old issue content, this should solve the problem that the issue mentions and we wont delete any further issues/pull requests unless they violate Github's terms of service.


schwizzlers (issue creator)

![image](https://github.com/user-attachments/assets/d79b01fd-eb67-4b07-aeee-442457f738f2)
-
regginator 

![image](https://github.com/user-attachments/assets/fb5dfc55-17b3-4c4d-b7a4-f370f8548422)
-
regginator 

![image](https://github.com/user-attachments/assets/7bf034f6-efe2-4c66-b8d1-9c1fde677916)
-
enbyte

![image](https://github.com/user-attachments/assets/4117832a-9fba-4243-acd0-8e37d9aacd4b)
-
regginator 

![image](https://github.com/user-attachments/assets/c7849581-1efe-443c-a466-b119a7d06cc1)
-
enbyte

![image](https://github.com/user-attachments/assets/abef4163-7e9d-4b5e-bdd9-9dc430819646)
-
regginator

![image](https://github.com/user-attachments/assets/f277eab9-c922-459f-b864-8a4dbbabcf80)
-
enbyte

![image](https://github.com/user-attachments/assets/51d49433-2f0c-4afc-a67a-0cfdb5828908)
-
regginator

![image](https://github.com/user-attachments/assets/6764a025-289a-4f2c-aaef-0925fcaefd6f)

**Comment by Trigus42** [comment]
Thanks for being so open in addressing my concerns!
